### ISSUE TITLE
如何查看或删除上传的图片？

### ISSUE THREAD

**Issue by zhutyler21** [uxiaohan/ZYCS-IMG#3]
不懂图床，我上传了一些图片，用于随时访问它们的url，但是现在不知道如何查看或删除了。
请大佬给些指示，谢谢！

**Comment by uxiaohan** [comment]
> 不懂图床，我上传了一些图片，用于随时访问它们的url，但是现在不知道如何查看或删除了。 请大佬给些指示，谢谢！

暂时未添加上传后存储URL链接功能，无法查看已上传的图片

**Comment by uxiaohan** [comment]
> 不懂图床，我上传了一些图片，用于随时访问它们的url，但是现在不知道如何查看或删除了。 请大佬给些指示，谢谢！

暂时未添加上传后存储图片URL功能，无法查看已上传的图片
因为图片托管在Telegraph上，无法删除
